version: '3.9'

name: hackaton

services:
  db:
    image: postgres:16
    container_name: hackaton_db
    restart: unless-stopped

    environment:
      - POSTGRES_USER=hackaton
      - POSTGRES_PASSWORD=hackaton123
    ports:
      - "5432:5432"

  backend:
    build:
      context: .

    container_name: hackaton_back
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - SERVER_PROTOCOL=http
      - SERVER_HOST=localhost:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/hackaton
      - SPRING_DATASOURCE_USERNAME=hackaton
      - SPRING_DATASOURCE_PASSWORD=hackaton123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8091:8080"
