name: CI/CD Dev

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: self-hosted
    name: 'Build and run artifact'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.2

    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'zulu'
        cache: maven
        
    - name: Build with Maven
      run: mvn package -Dmaven.test.skip
      
    - name: Run services
      run: |          
          docker compose -f "./docker-compose.yml" pull
          docker compose -f "./docker-compose.yml" down
          docker compose -f "./docker-compose.yml" up -d --no-deps --build backend
          docker system prune -a -f
